# Generated by Django 2.1.1 on 2018-11-20 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20181112_2350'),
        ('menu', '0005_auto_20181113_0931'),
    ]

    operations = [
    ]
